# 通过以下命令确定 Authorization
# curl -v -X GET --user elastic:8E78NY1mnfGvQJ6e7aHy http://nudocker01:9120/

### 创建 topic_filter index
PUT {{esUrl}}/topic_filter
Content-Type: application/json
Authorization: Basic {{token}}

{
  "settings": {
    "index.number_of_shards": 3,
    "index.number_of_replicas": 1
  },
  "mappings": {
    "dynamic": "false",
    "properties": {
      "topicLevel": {
        "properties": {
          "0": {
            "type": "keyword"
          },
          "1": {
            "type": "keyword"
          },
          "2": {
            "type": "keyword"
          },
          "3": {
            "type": "keyword"
          },
          "4": {
            "type": "keyword"
          },
          "5": {
            "type": "keyword"
          },
          "6": {
            "type": "keyword"
          },
          "7": {
            "type": "keyword"
          },
          "8": {
            "type": "keyword"
          },
          "9": {
            "type": "keyword"
          },
          "10": {
            "type": "keyword"
          },
          "11": {
            "type": "keyword"
          },
          "12": {
            "type": "keyword"
          }
        }
      },
      "value": {
        "type": "keyword"
      },
      "nodes": {
        "type": "keyword"
      },
      "offlineSubscriptions": {
        "properties": {
          "clientIdentifier": {
            "type": "keyword"
          },
          "qos": {
            "type": "byte"
          }
        }
      }
    }
  }
}

### 创建 session_queue index
PUT {{esUrl}}/session_queue
Content-Type: application/json
Authorization: Basic {{token}}

{
  "settings": {
    "index.number_of_shards": 3,
    "index.number_of_replicas": 1,
    "refresh_interval": "10m"
  },
  "mappings": {
    "dynamic": "false",
    "properties": {
      "id": {
        "type": "keyword"
      },
      "clientIdentifier": {
        "type": "keyword"
      },
      "type": {
        "type": "keyword"
      },
      "packetIdentifier": {
        "type": "short"
      },
      "status": {
        "type": "keyword"
      },
      "publish": {
        "type": "binary"
      },
      "createdAt": {
        "type": "date"
      },
      "updatedAt": {
        "type": "date"
      },
      "nextPacketIdentifier": {
        "type": "short"
      }
    }
  }
}

### 创建 session index
PUT {{esUrl}}/session
Content-Type: application/json
Authorization: Basic {{token}}

{
  "settings": {
    "index.number_of_shards": 3,
    "index.number_of_replicas": 1
  },
  "mappings": {
    "dynamic": "false",
    "properties": {
      "clientIdentifier": {
        "type": "keyword"
      },
      "nodeId": {
        "type": "keyword"
      },
      "outQueuePacketIdentifier": {
        "type": "short"
      },
      "subscriptions": {
        "properties": {
          "topicFilter": {
            "type": "keyword"
          },
          "qos": {
            "type": "byte"
          }
        }
      }
    }
  }
}


### delete index: topic_filter
DELETE {{esUrl}}/topic_filter
Content-Type: application/json
Authorization: Basic {{token}}

###
DELETE {{esUrl}}/session_queue
Content-Type: application/json
Authorization: Basic {{token}}

###
DELETE {{esUrl}}/session
Content-Type: application/json
Authorization: Basic {{token}}


